import NavMenu from '@/components/NavMenu';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <NavMenu />

        <main className='py-10 px-6 lg:pt-28'>
          {children}
        </main>

      </body>
    </html>
  )
}
